//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub_2_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Speaker.
    /// </summary>
    // *** Start programmer edit section *** (Speaker CustomAttributes)

    // *** End programmer edit section *** (Speaker CustomAttributes)
    [PrimaryKeyStorage("Id")]
    [AutoAltered()]
    [Caption("Спикер")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SpeakerE", new string[] {
            "Foto as \'Фотография\'",
            "LastName as \'Фамилия\'",
            "FirstName as \'Имя\'",
            "MiddleName as \'Отчество\'"})]
    [View("SpeakerFull", new string[] {
            "Foto",
            "LastName",
            "FirstName",
            "MiddleName",
            "fullName"})]
    [View("SpeakerFullShort", new string[] {
            "Foto",
            "fullName"})]
    [View("SpeakerL", new string[] {
            "Foto as \'Фотография\'",
            "LastName as \'Фамилия\'",
            "FirstName as \'Имя\'",
            "MiddleName as \'Отчество\'"})]
    public class Speaker : ICSSoft.STORMNET.DataObject
    {
        
        private string fFirstName;
        
        private string fLastName;
        
        private string fMiddleName;
        
        private ICSSoft.STORMNET.UserDataTypes.WebFile fFoto;
        
        // *** Start programmer edit section *** (Speaker CustomMembers)

        // *** End programmer edit section *** (Speaker CustomMembers)

        
        /// <summary>
        /// FirstName.
        /// </summary>
        // *** Start programmer edit section *** (Speaker.FirstName CustomAttributes)

        // *** End programmer edit section *** (Speaker.FirstName CustomAttributes)
        [StrLen(255)]
        public virtual string FirstName
        {
            get
            {
                // *** Start programmer edit section *** (Speaker.FirstName Get start)

                // *** End programmer edit section *** (Speaker.FirstName Get start)
                string result = this.fFirstName;
                // *** Start programmer edit section *** (Speaker.FirstName Get end)

                // *** End programmer edit section *** (Speaker.FirstName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Speaker.FirstName Set start)

                // *** End programmer edit section *** (Speaker.FirstName Set start)
                this.fFirstName = value;
                // *** Start programmer edit section *** (Speaker.FirstName Set end)

                // *** End programmer edit section *** (Speaker.FirstName Set end)
            }
        }
        
        /// <summary>
        /// LastName.
        /// </summary>
        // *** Start programmer edit section *** (Speaker.LastName CustomAttributes)

        // *** End programmer edit section *** (Speaker.LastName CustomAttributes)
        [StrLen(255)]
        public virtual string LastName
        {
            get
            {
                // *** Start programmer edit section *** (Speaker.LastName Get start)

                // *** End programmer edit section *** (Speaker.LastName Get start)
                string result = this.fLastName;
                // *** Start programmer edit section *** (Speaker.LastName Get end)

                // *** End programmer edit section *** (Speaker.LastName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Speaker.LastName Set start)

                // *** End programmer edit section *** (Speaker.LastName Set start)
                this.fLastName = value;
                // *** Start programmer edit section *** (Speaker.LastName Set end)

                // *** End programmer edit section *** (Speaker.LastName Set end)
            }
        }
        
        /// <summary>
        /// MiddleName.
        /// </summary>
        // *** Start programmer edit section *** (Speaker.MiddleName CustomAttributes)

        // *** End programmer edit section *** (Speaker.MiddleName CustomAttributes)
        [StrLen(255)]
        public virtual string MiddleName
        {
            get
            {
                // *** Start programmer edit section *** (Speaker.MiddleName Get start)

                // *** End programmer edit section *** (Speaker.MiddleName Get start)
                string result = this.fMiddleName;
                // *** Start programmer edit section *** (Speaker.MiddleName Get end)

                // *** End programmer edit section *** (Speaker.MiddleName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Speaker.MiddleName Set start)

                // *** End programmer edit section *** (Speaker.MiddleName Set start)
                this.fMiddleName = value;
                // *** Start programmer edit section *** (Speaker.MiddleName Set end)

                // *** End programmer edit section *** (Speaker.MiddleName Set end)
            }
        }
        
        /// <summary>
        /// Foto.
        /// </summary>
        // *** Start programmer edit section *** (Speaker.Foto CustomAttributes)

        // *** End programmer edit section *** (Speaker.Foto CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.WebFile Foto
        {
            get
            {
                // *** Start programmer edit section *** (Speaker.Foto Get start)

                // *** End programmer edit section *** (Speaker.Foto Get start)
                ICSSoft.STORMNET.UserDataTypes.WebFile result = this.fFoto;
                // *** Start programmer edit section *** (Speaker.Foto Get end)

                // *** End programmer edit section *** (Speaker.Foto Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Speaker.Foto Set start)

                // *** End programmer edit section *** (Speaker.Foto Set start)
                this.fFoto = value;
                // *** Start programmer edit section *** (Speaker.Foto Set end)

                // *** End programmer edit section *** (Speaker.Foto Set end)
            }
        }
        
        /// <summary>
        /// fullName.
        /// </summary>
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        [TrimmedStringStorage(false)]
        public virtual string fullName
        {
            get
            {
                // *** Start programmer edit section *** (Speaker.fullName Get)

                return null;
                // *** End programmer edit section *** (Speaker.fullName Get)
            }
            set
            {
                // *** Start programmer edit section *** (Speaker.fullName Set)

                // *** End programmer edit section *** (Speaker.fullName Set)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SpeakerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpeakerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpeakerE", typeof(IIS.BookClub_2_1.Speaker));
                }
            }
            
            /// <summary>
            /// "SpeakerFull" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpeakerFull
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpeakerFull", typeof(IIS.BookClub_2_1.Speaker));
                }
            }
            
            /// <summary>
            /// "SpeakerFullShort" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpeakerFullShort
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpeakerFullShort", typeof(IIS.BookClub_2_1.Speaker));
                }
            }
            
            /// <summary>
            /// "SpeakerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpeakerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpeakerL", typeof(IIS.BookClub_2_1.Speaker));
                }
            }
        }
    }
}
